# Generated by Django 5.0.6 on 2024-07-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('registration_number', models.CharField(max_length=50)),
                ('total_farmers', models.IntegerField()),
                ('total_loans_given', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_loans_repaid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
